---
  - name: Add repository
    yum_repository:
      name: mongodb-org-3.4
      description: Official MongoDB 3.4 yum repo
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
      gpgcheck: 1
      gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc

  - name: Install MongoDB packages on the mongos servers
    yum:
      name: ["mongodb-org",
             "mongodb-org-mongos",
             "mongodb-org-server",
             "mongodb-org-shell",
             "mongodb-org-tools"]
      enablerepo: "mongodb-org-3.4"
      state: "installed"
    when: ansible_hostname in groups['mongos']

  - name: Install MongoDB packages on the shard servers
    yum:
      name: ["mongodb-org-server",
             "mongodb-org-shell",
             "mongodb-org-tools"]
      enablerepo: "mongodb-org-3.4"
      state: "installed"
    when: ansible_hostname in groups['mongod']

  - name: Ensure files and directories are owned by mongod
    file:
      path: ["/var/log/mongodb/", "/var/lib/mongo", "/var/run/mongodb/mongod.pid"]
      owner: "mongod"
      group: "mongod"
      recurse: "yes"

  - name: Add hostname.local to /etc/hosts
    lineinfile:
      path: "/etc/hosts"
      regexp: "^127.0.0.1 {{ansible_hostname}}.local"
      line: "127.0.0.1 {{ansible_hostname}}.local"

  - name: Copy mongod config file to hosts
    template:
      src: "../templates/mongod.conf"
      dest: "/etc/mongod.conf"
      backup: "yes"
      owner: "mongod"
      group: "mongod"
      mode: 0644
    when: ansible_hostname in item['members'] | regex_replace("\\.local", "") and ansible_hostname in groups['mongod']
    with_items: "{{ mongodb_shards }}"

  - name: Ensure mongod service is running
    service:
      name: "mongod"
      state: "started"

  - name: Give mongod daemon a little time
    pause:
      seconds: 30

    # TODO Replace with template?
  - name: Copy Shard Setup Script to lead node of each shard
    copy:
      content: |
         rs.initiate();
         while(rs.status()['myState'] != 1) {
              print("State is not yet PRIMARY. Waiting...");
              sleep(10000);
         }
         rs.add("{{ item['members'][1] }}:27017");
         rs.add("{{ item['members'][2] }}:27017");
         sleep(10000);
         var doc = rs.status();
         if(doc['members'].length == 3) {
            quit(0);
         }
         else {
            quit(1);
         }
      dest: /home/vagrant/sharding.js
    when: ansible_hostname == item['members'][0] | regex_replace("\\.local", "") and ansible_hostname in groups['mongod']
    with_items: "{{ mongodb_shards }}"

  - name: Execute Shard Setup Script on each lead node_name
    command: mongo /home/vagrant/sharding.js
    args:
      creates: /home/vagrant/sharding.success
    register: sharding
    when: ansible_hostname == item['members'][0] | regex_replace("\\.local", "") and ansible_hostname in groups['mongod']
    with_items: "{{ mongodb_shards }}"
